In [2]:
import requests
import pandas as pd

In [3]:
data=requests.get("https://api.github.com/repos/PhonePe/pulse/contents/data/aggregated/transaction/country/india/state?ref=master")

In [4]:
data

In [5]:
# for i in data.json():
#     if i["type"]=="dir":
#         print(i["name"])
states=[]
for x in data.json():
    states.append(x["name"])

In [6]:
states

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [7]:
def clean_state(name):
    name = name.lower()
    name = name.replace("-", " ")
    name = name.replace("&", "and")
    return name.strip()

In [8]:
resp=requests.get("https://raw.githubusercontent.com/PhonePe/pulse/refs/heads/master/data/aggregated/transaction/country/india/state/andaman-%26-nicobar-islands/2024/4.json")

In [9]:
resp

In [10]:
pd.set_option('display.float_format', lambda num: '%.0f' % num)

In [11]:
resp.json()

{'success': True,
 'code': 'SUCCESS',
 'data': {'from': 1727740800000,
  'to': 1735344000000,
  'transactionData': [{'name': 'Merchant payments',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 3666060,
      'amount': 2546601178.0}]},
   {'name': 'Peer-to-peer payments',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 1993301,
      'amount': 6142805445.0}]},
   {'name': 'Recharge & bill payments',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 389318,
      'amount': 214912264.0}]},
   {'name': 'Financial Services',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 12889,
      'amount': 12789955.0}]},
   {'name': 'Others',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 2332,
      'amount': 3835931.0}]}]},
 'responseTimestamp': 1739974461977}

In [12]:
resp.json()["data"]["transactionData"] #["name"]["paymentInstruments"]["count"]["ammount"]

[{'name': 'Merchant payments',
  'paymentInstruments': [{'type': 'TOTAL',
    'count': 3666060,
    'amount': 2546601178.0}]},
 {'name': 'Peer-to-peer payments',
  'paymentInstruments': [{'type': 'TOTAL',
    'count': 1993301,
    'amount': 6142805445.0}]},
 {'name': 'Recharge & bill payments',
  'paymentInstruments': [{'type': 'TOTAL',
    'count': 389318,
    'amount': 214912264.0}]},
 {'name': 'Financial Services',
  'paymentInstruments': [{'type': 'TOTAL',
    'count': 12889,
    'amount': 12789955.0}]},
 {'name': 'Others',
  'paymentInstruments': [{'type': 'TOTAL',
    'count': 2332,
    'amount': 3835931.0}]}]

In [13]:
f=[]
t_count=0
t_amount=0
state="andaman-&-nicobar-islands"
for i in resp.json()["data"]["transactionData"]:
    # print(i['paymentInstruments'])
    for j in i['paymentInstruments']:
        t_count+=j["count"]
        t_amount+=j["amount"]
f.append({"state":state,"count":t_count,"amount":t_amount})
        
dms=pd.DataFrame(f)

In [14]:
dms

                       state    count     amount
0  andaman-&-nicobar-islands  6063900 8920944773

In [15]:
for i in resp.json()["data"]["transactionData"]:
    print(i['paymentInstruments'][0]["amount"])

2546601178.0
6142805445.0
214912264.0
12789955.0
3835931.0

In [16]:
url="https://raw.githubusercontent.com/PhonePe/pulse/refs/heads/master/data/aggregated/transaction/country/india/state/{S}/{y}/{q}.json"
raw=[]
for s in states:
    rp=requests.get(url.format(S=s,y=2024,q=4))
    if rp.status_code != 200:
        print("FAILED:", s, rp.status_code)
        continue
    t_count=0
    t_amount=0
    for i in rp.json()["data"]["transactionData"]:
            t_count+=(i['paymentInstruments'][0]["count"])
            t_amount+=(i['paymentInstruments'][0]["amount"])
    raw.append({"state":s,"count":t_count,"amount":t_amount})
    
df=pd.DataFrame(raw)
df

                                 state       count        amount
0            andaman-&-nicobar-islands     6063900    8920944773
1                       andhra-pradesh  2296445544 3452015568966
2                    arunachal-pradesh    26793457   35079886873
3                                assam   332441531  382786405959
4                                bihar  1559667675 2098927476047
5                           chandigarh    18528444   20501385889
6                         chhattisgarh   500655404  576828444625
7   dadra-&-nagar-haveli-&-daman-&-diu    28463700   23945221461
8                                delhi   910543082 1057060485903
9                                  goa    46131536   56562589543
10                             gujarat   827374966 1076014501422
11                             haryana   841394290 1031959359354
12                    himachal-pradesh    53798398   63736996234
13                     jammu-&-kashmir   126261217  160950980732
14                           jharkhand   586904686  704010501034
15                           karnataka  3455056424 4151819803822
16                              kerala   233112441  273639970566
17                              ladakh     5711284   10854417654
18                         lakshadweep      197777     247756681
19                      madhya-pradesh  1685401835 2003305068845
20                         maharashtra  3634231839 4151028450887
21                             manipur     5750423   12061708556
22                           meghalaya    14166380   19674927433
23                             mizoram     2702443    4461162922
24                            nagaland     7921552   13959098676
25                              odisha  1143097568 1305457593239
26                          puducherry    16559677   19965392547
27                              punjab   199509220  289125652032
28                           rajasthan  2043469547 2793049371408
29                              sikkim     8916870   12641101398
30                          tamil-nadu   820423888 1087632875606
31                           telangana  2822451603 3859050535418
32                             tripura    15945159   22409905268
33                       uttar-pradesh  2544890265 3214106522459
34                         uttarakhand   171136132  194908790959
35                         west-bengal  1227135682 1810100029406

In [17]:
url="https://raw.githubusercontent.com/PhonePe/pulse/refs/heads/master/data/aggregated/transaction/country/india/state/{S}/{Y}/{Q}.json"
years=[2018,2019,2020,2021,2022,2023,2024]
s="maharashtra"
raw=[]
for y in years:
    for q in range(1,5):
        rp=requests.get(url.format(S=s,Y=y,Q=q))
        if rp.status_code != 200:
            print("FAILED:", s, rp.status_code)
            continue
        t_count=0
        t_amount=0
        for i in rp.json()["data"]["transactionData"]:
                t_count+=(i['paymentInstruments'][0]["count"])
                t_amount+=(i['paymentInstruments'][0]["amount"])
        raw.append({"state":s,"year":y,"quarter":q,"count":t_count,"amount":t_amount})
    
dm=pd.DataFrame(raw)
dm

          state  year  quarter       count        amount
0   maharashtra  2018        1    16387034   21711613258
1   maharashtra  2018        2    22285740   36357057241
2   maharashtra  2018        3    31538538   52260817733
3   maharashtra  2018        4    46090223   79518937048
4   maharashtra  2019        1    75079069  111420690920
5   maharashtra  2019        2   101149853  153294470088
6   maharashtra  2019        3   148735581  199617506745
7   maharashtra  2019        4   201260620  272994428800
8   maharashtra  2020        1   238944081  319995196718
9   maharashtra  2020        2   184790761  296359517159
10  maharashtra  2020        3   268310924  440307079012
11  maharashtra  2020        4   407621004  622155530832
12  maharashtra  2021        1   517860240  769887352153
13  maharashtra  2021        2   573616486  915115055624
14  maharashtra  2021        3   792874060 1159257305167
15  maharashtra  2021        4  1010731502 1475358473129
16  maharashtra  2022        1  1169506438 1681399273981
17  maharashtra  2022        2  1407533113 2006272382176
18  maharashtra  2022        3  1486389417 1947579187375
19  maharashtra  2022        4  1688775272 2210470839617
20  maharashtra  2023        1  1848268499 2362285906059
21  maharashtra  2023        2  2063717848 2606004606468
22  maharashtra  2023        3  2290678587 2752172184241
23  maharashtra  2023        4  2572162725 3098014934958
24  maharashtra  2024        1  2835770481 3372898894856
25  maharashtra  2024        2  3063494802 3573189333587
26  maharashtra  2024        3  3287403995 3687268662139
27  maharashtra  2024        4  3634231839 4151028450887

In [18]:
ds=pd.read_csv("..//data//raw//ndap_gst//Goods and Service Tax Returns.csv")

In [19]:
ds.shape

(7828, 12)

In [20]:
phonepe_set = {clean_state(s) for s in df["state"]}
ndap_set = {clean_state(s) for s in ds["State"].unique()}

In [21]:
print("In PhonePe, not in NDAP:", phonepe_set - ndap_set)
print("In NDAP, not in PhonePe:", ndap_set - phonepe_set)

In PhonePe, not in NDAP: {'dadra and nagar haveli and daman and diu'}
In NDAP, not in PhonePe: {'dadra and nagar haveli', 'daman and diu', 'other territory'}

In [22]:
pd.read_csv("../src/clean/state_mapping.csv")

  source              clean_name                           canonical_state
0   ndap  dadra and nagar haveli  dadra and nagar haveli and daman and diu
1   ndap           daman and diu  dadra and nagar haveli and daman and diu
2   ndap         other territory                                      DROP

In [24]:
ds["month_date"] = pd.to_datetime(ds["Month"], format="%B, %Y")
ds["quarter"] = ds["month_date"].dt.to_period("Q")

print(ds["month_date"].min())
print(ds["month_date"].max())
print(ds["quarter"].nunique())

2017-07-01 00:00:00
2026-01-01 00:00:00
35

In [25]:
window = pd.period_range("2018Q1", "2024Q4", freq="Q")
print(len(window))
print(window.isin(ds["quarter"]).all())

28
True

In [26]:
cpi=pd.read_excel("../data/raw/cpi/cpi_1520.xlsx")

In [27]:
cpi

,baseyear,year,month_code,month,state,sector,group,subgroup,index,inflation,status
0,2012,2025,12,December,Andaman & Nicobar Islands,Rural,Miscellaneous,Miscellaneous-Overall,191,1,F
1,2012,2025,12,December,Andaman & Nicobar Islands,Rural,Fuel and Light,Fuel and Light-Overall,161,2,F
2,2012,2025,12,December,Andaman & Nicobar Islands,Rural,Housing,Housing-Overall,NaN,NaN,F
3,2012,2025,12,December,Andaman & Nicobar Islands,Rural,Clothing and Footwear,Clothing and Footwear-Overall,185,-4,F
4,2012,2025,12,December,Andaman & Nicobar Islands,Rural,"Pan, Tobacco and Intoxicants","Pan, Tobacco and Intoxicants-Overall",217,5,F
...,...,...,...,...,...,...,...,...,...,...,...
213829,2012,2017,1,January,West Bengal,Combined,Food and Beverages,"Prepared Meals, Snacks, Sweets etc.",144,5,F
213830,2012,2017,1,January,West Bengal,Combined,Food and Beverages,Non-alcoholic Beverages,129,4,F
213831,2012,2017,1,January,West Bengal,Combined,Food and Beverages,Spices,129,6,F
213832,2012,2017,1,January,West Bengal,Combined,Food and Beverages,Meat and Fish,135,3,F
213833,2012,2017,1,January,West Bengal,Combined,General,General-Overall,129,3,F

In [28]:
small=cpi[(cpi["group"]=="General")&
    (cpi["subgroup"]=="General-Overall")&
    (cpi["sector"] == "Combined")]

In [29]:
small

,baseyear,year,month_code,month,state,sector,group,subgroup,index,inflation,status
20,2012,2025,12,December,Andaman & Nicobar Islands,Combined,General,General-Overall,200,1,F
101,2012,2025,12,December,Andhra Pradesh,Combined,General,General-Overall,205,3,F
119,2012,2025,12,December,Arunachal Pradesh,Combined,General,General-Overall,NaN,NaN,F
200,2012,2025,12,December,Assam,Combined,General,General-Overall,197,-1,F
281,2012,2025,12,December,Bihar,Combined,General,General-Overall,194,-1,F
...,...,...,...,...,...,...,...,...,...,...,...
213569,2012,2017,1,January,Telangana,Combined,General,General-Overall,132,5,F
213590,2012,2017,1,January,Tripura,Combined,General,General-Overall,137,3,F
213671,2012,2017,1,January,Uttarakhand,Combined,General,General-Overall,124,3,F
213752,2012,2017,1,January,Uttar Pradesh,Combined,General,General-Overall,129,3,F
213833,2012,2017,1,January,West Bengal,Combined,General,General-Overall,129,3,F

In [30]:
small.shape

(3813, 11)

In [31]:
small["state"].nunique()

36